### PR TITLE
New YAML-based syntax

### LINKED ISSUE #27: Introduce expansion for file extensions
To write something like: `{/?file image: rose.(jpg,jpeg)}` to be expanded to `{/?file image: rose.jpg rose.jpeg}` to resemble alternative's syntax in code description.

## Notes

- parenthesis should not be escaped
- spacing after . doesn't matter
- spacing between extensions doesn't matter
- no extension can have escaped space in it

### LINKED ISSUE #28: Introduce better expansion syntax for ranges
Use parenthesis instead of `..` for ranges: `{int priority: (1, 10)}`. Also add an ability to refer the first or the last range border inside expansions like `{int priority: (10, $from + 20)}`. In other words allow +, -, *, /, % operators and `$from`, `$to` variables inside ranges. Note that just one range border can have math expression, not both and it's not possible to refer to anything outside of the current range.

## Notes

- parenthesis should not be escaped
- spacing doesn't matter

### LINKED ISSUE #30: Introduce new syntax for so named "comprehensive placeholders"
Such placeholder guarantee that they list all possible valid values suitable to perform some task presented in any code example. Possible syntax: `{keyword! description: examples}`, like `{bool! whether to enable delayed expansion: on, off}`.

This solves a huge issue inherited from TlDr where user can just guess whether all possible values are shown in placeholder. By all means intuitively boolean placeholders are comprehensive and it makes sense as there are just two possible values. But for more complex things it's not always obvious and one standardized way should be introduced to explain whether all valid values are listed. Such feature will be useful for enum-like values.

### LINKED ISSUE #31: Introduce concept of placeholder annotations
The goal is to allow provide details for placeholders in a readable way like `{/?file @require-extension}`.

### LINKED ISSUE #35: Solve issue with {option ...} placeholder
Option now accepts just two arguments and intended to show long or short options. But it [breaks](https://github.com/command-line-interface-pages/cli-pages/pull/32) standardization and makes impossible to write something like this:

```md
- Display differences in [d]ecimal/[a]SCII format:

`comp {option format: /d, /a} {/?file file 1} {/?file file 2}`
```

This workaround:

```md
- Display differences in [d]ecimal/[a]SCII format:

`comp {option decimal format: /d|option ASCII format: /a} {/?file file 1} {/?file file 2}`
```

results in unsupported placeholder.

## How to solve?

- Permit any number of examples for option.
- But treat them specially (as short - long option pair) when GNU-style long and short option are both provided (it keeps backward compatibility).

On the other hand I can introduce [comprehensive placeholders](https://github.com/command-line-interface-pages/syntax/issues/30) first and then make option placeholder comprehensive. It makes sense to always list all available options in the context of some code example.

### LINKED ISSUE #36: Complete migration to YAML
# Task

Migrate to YAML completely.

# Motivation

It's better to use well-known syntax then extending Markdown with some special constructs. Furthermore it's much easier provide Intellisence for YAML via JSON schema then writing my own LSP server for Markdown-like language.

Also, directory pages require tags for examples to specify for instance whether some subdirectory or file is optional. It will be easier to do in YAML. 

# Notes

Migration should be done in automatic mode, via CLIP -> YAML converter.

### LINKED ISSUE #39: Introduce concept of page tag inheritance
It will be useful when several commands share the same tag values, like identical help/value flags.

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
Why to reinvent something when we can just use YAML as the syntax base? It will be much simpler to add some attributes to examples or page summary and extract them via yq or Go then parsing everything manually.

closes #30 
closes #31 
closes #35 
closes #39

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
@blueglyph, can u review this PR?

**Comment by blueglyph** [comment]
@EmilySeville7cfg Why do you ask me? I'm not in the project. I wouldn't even know where to start and to be honest, I'm a little swamped at the moment, sorry.

**Comment by EmilySeville7cfg** [comment]
I thought that it may be interesting, sorry

**Review by mfrw — COMMENTED** [review]
Great work.
Not able to review the full PR .. will do it in another pass :)
⌛

**Comment by EmilySeville7cfg** [comment]
@mfrw, btw, now syntax is validated via JSON schema. ;)

**Pull request merged**
